# Generated by Django 5.2.7 on 2025-11-08 14:59

import django.db.models.deletion
import pc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('allow_multiple', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrebuiltPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=pc.models.prebuilt_image_upload_path)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processor', models.CharField(max_length=255)),
                ('motherboard', models.CharField(max_length=255)),
                ('graphics_card', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('storage', models.CharField(max_length=255)),
                ('power_supply', models.CharField(max_length=255)),
                ('cooling', models.CharField(blank=True, max_length=255, null=True)),
                ('cabinet', models.CharField(blank=True, max_length=255, null=True)),
                ('monitor', models.CharField(blank=True, max_length=255, null=True)),
                ('accessories', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Prebuilt PC',
                'verbose_name_plural': 'Prebuilt PCs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=pc.models.product_image_upload_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveBigIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='pc.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PowerSupplyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wattage', models.PositiveIntegerField()),
                ('efficiency_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('modular', models.BooleanField(default=False)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='powersupply_details', to='pc.product')),
            ],
        ),
        migrations.CreateModel(
            name='MotherboardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chipset', models.CharField(max_length=50)),
                ('socket_type', models.CharField(max_length=50)),
                ('form_factor', models.CharField(max_length=20)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motherboard_details', to='pc.product')),
            ],
        ),
        migrations.CreateModel(
            name='MonitorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_inch', models.DecimalField(decimal_places=1, max_digits=4)),
                ('resolution', models.CharField(max_length=50)),
                ('refresh_rate_hz', models.PositiveIntegerField()),
                ('panel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_details', to='pc.product')),
            ],
        ),
        migrations.CreateModel(
            name='GPUDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vram_gb', models.PositiveIntegerField()),
                ('chipset', models.CharField(max_length=100)),
                ('interface', models.CharField(default='PCIe 4.0', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpu_details', to='pc.product')),
            ],
        ),
        migrations.CreateModel(
            name='CPUDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_count', models.PositiveIntegerField()),
                ('thread_count', models.PositiveIntegerField()),
                ('base_clock_ghz', models.DecimalField(decimal_places=2, max_digits=4)),
                ('socket_type', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpu_details', to='pc.product')),
            ],
        ),
        migrations.CreateModel(
            name='CoolingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooling_type', models.CharField(max_length=50)),
                ('fan_count', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cooling_details', to='pc.product')),
            ],
        ),
        migrations.CreateModel(
            name='CabinetDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_factor', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_details', to='pc.product')),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_type', models.CharField(choices=[('Mouse', 'Mouse'), ('Keyboard', 'Keyboard'), ('Headset', 'Headset'), ('Monitor', 'Monitor'), ('Other', 'Other')], max_length=20)),
                ('connection', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_details', to='pc.product')),
            ],
        ),
        migrations.CreateModel(
            name='RAMDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_gb', models.PositiveIntegerField()),
                ('speed_mhz', models.PositiveIntegerField()),
                ('ddr_type', models.CharField(max_length=10)),
                ('module_count', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ram_details', to='pc.product')),
            ],
        ),
        migrations.CreateModel(
            name='StorageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_gb', models.PositiveIntegerField()),
                ('storage_type', models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD'), ('NVMe', 'NVMe SSD')], max_length=10)),
                ('form_factor', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_details', to='pc.product')),
            ],
        ),
    ]
