# Generated by Django 5.2.7 on 2025-11-14 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpudetails',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cpu_details', to='pc.product'),
        ),
        migrations.AlterField(
            model_name='gpudetails',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gpu_details', to='pc.product'),
        ),
        migrations.AlterField(
            model_name='ramdetails',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ram_details', to='pc.product'),
        ),
        migrations.AlterField(
            model_name='storagedetails',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_details', to='pc.product'),
        ),
    ]
