# Generated by Django 5.2.7 on 2025-11-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0004_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powersupplydetails',
            name='modular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
