# Generated by Django 5.2.7 on 2025-11-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0005_alter_powersupplydetails_modular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powersupplydetails',
            name='efficiency_rating',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
