# Generated by Django 5.2.7 on 2026-01-04 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0008_orderitem_prebuilt_pc_alter_orderitem_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(blank=True, max_length=15)),
                ('user_address', models.TextField(blank=True)),
                ('user_city', models.CharField(blank=True, max_length=100)),
                ('user_state', models.CharField(blank=True, max_length=100)),
                ('user_pincode', models.CharField(blank=True, max_length=10)),
                ('user_image', models.ImageField(blank=True, default='profiles/default.png', null=True, upload_to='profiles/')),
                ('profile_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
